name: Api Tester
run-name: testing out GitHub Actions 🚀
on: [push]
# on:
#   pull_request:
#     types:
#       - opened
    # branches:
    #   - 'dev/**'
jobs:
  Test-Api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check out repository code
        uses: actions/setup-node@v2

        run: git clone https://github.com/Esoty-Software-Solutions/APItester.git 
        run: cd APItester
        run: npm install
        run: npm run test