name: Api Tester
run-name: testing out GitHub Actions 🚀
on: [push]
# on:
#   pull_request:
#     types:
#       - opened
    # branches:
    #   - 'dev/**'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: get test repo
        uses: actions/setup-node@v2
      - run: git clone https://github.com/Esoty-Software-Solutions/APItester.git 
      - name: start test
      - run: cd APItester
      - run: npm install
      - run: npm run test